/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from './RewardsVestingOrchestrator.types';
import * as _1 from './RewardsVestingOrchestrator.client';
import * as _2 from './Vesting.types';
import * as _3 from './Vesting.client';
export namespace contracts {
  export const RewardsVestingOrchestrator = {
    ..._0,
    ..._1,
  };
  export const Vesting = {
    ..._2,
    ..._3,
  };
}
