/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import {
  CosmWasmClient,
  SigningCosmWasmClient,
  ExecuteResult,
} from '@cosmjs/cosmwasm-stargate';
import { Coin, StdFee } from '@cosmjs/amino';
import {
  ExecuteMsg,
  Schedule,
  Uint128,
  Timestamp,
  Uint64,
  Action,
  Expiration,
  VestingConfiguration,
  VestingRecord,
  GetAllVestingContractsResponse,
  VestingContractRecord,
  InstantiateMsg,
  QueryMsg,
  VestingContractResponse,
} from './RewardsVesting.types';
export interface RewardsVestingReadOnlyInterface {
  contractAddress: string;
  vestingContract: ({
    address,
  }: {
    address: string;
  }) => Promise<VestingContractResponse>;
  allVestingContracts: ({
    limit,
    startAfter,
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<AllVestingContractsResponse>;
}
export class RewardsVestingQueryClient
  implements RewardsVestingReadOnlyInterface
{
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.vestingContract = this.vestingContract.bind(this);
    this.allVestingContracts = this.allVestingContracts.bind(this);
  }
  vestingContract = async ({
    address,
  }: {
    address: string;
  }): Promise<VestingContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vesting_contract: {
        address,
      },
    });
  };
  allVestingContracts = async ({
    limit,
    startAfter,
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<AllVestingContractsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_vesting_contracts: {
        limit,
        start_after: startAfter,
      },
    });
  };
}
export interface RewardsVestingInterface
  extends RewardsVestingReadOnlyInterface {
  contractAddress: string;
  sender: string;
  batchVesting: (
    {
      configuration,
      records,
    }: {
      configuration: VestingConfiguration;
      records: VestingRecord[];
    },
    fee_?: number | StdFee | 'auto',
    memo_?: string,
    funds_?: Coin[],
  ) => Promise<ExecuteResult>;
  batchCancel: (
    {
      addresses,
    }: {
      addresses: string[];
    },
    fee_?: number | StdFee | 'auto',
    memo_?: string,
    funds_?: Coin[],
  ) => Promise<ExecuteResult>;
  updateOwnership: (
    action: Action,
    fee_?: number | StdFee | 'auto',
    memo_?: string,
    funds_?: Coin[],
  ) => Promise<ExecuteResult>;
}
export class RewardsVestingClient
  extends RewardsVestingQueryClient
  implements RewardsVestingInterface
{
  declare client: SigningCosmWasmClient;
  sender: string;
  declare contractAddress: string;
  constructor(
    client: SigningCosmWasmClient,
    sender: string,
    contractAddress: string,
  ) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.batchVesting = this.batchVesting.bind(this);
    this.batchCancel = this.batchCancel.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  batchVesting = async (
    {
      configuration,
      records,
    }: {
      configuration: VestingConfiguration;
      records: VestingRecord[];
    },
    fee_: number | StdFee | 'auto' = 'auto',
    memo_?: string,
    funds_?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        batch_vesting: {
          configuration,
          records,
        },
      },
      fee_,
      memo_,
      funds_,
    );
  };
  batchCancel = async (
    {
      addresses,
    }: {
      addresses: string[];
    },
    fee_: number | StdFee | 'auto' = 'auto',
    memo_?: string,
    funds_?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        batch_cancel: {
          addresses,
        },
      },
      fee_,
      memo_,
      funds_,
    );
  };
  updateOwnership = async (
    action: Action,
    fee_: number | StdFee | 'auto' = 'auto',
    memo_?: string,
    funds_?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_ownership: action,
      },
      fee_,
      memo_,
      funds_,
    );
  };
}
