/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type ExecuteMsg =
  | {
      batch_vesting: {
        configuration: VestingConfiguration;
        records: VestingRecord[];
      };
    }
  | {
      batch_cancel: {
        addresses: string[];
      };
    }
  | {
      update_ownership: Action;
    };
export type Schedule =
  | 'saturating_linear'
  | {
      piecewise_linear: [number, Uint128][];
    };
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type Action =
  | {
      transfer_ownership: {
        expiry?: Expiration | null;
        new_owner: string;
      };
    }
  | 'accept_ownership'
  | 'renounce_ownership';
export type Expiration =
  | {
      at_height: number;
    }
  | {
      at_time: Timestamp;
    }
  | {
      never: {};
    };
export interface VestingConfiguration {
  contract_code_id: number;
  denom: string;
  description_prefix: string;
  duration: number;
  schedule: Schedule;
  start_time: Timestamp;
  title_prefix: string;
}
export interface VestingRecord {
  address: string;
  amount: Uint128;
}
export interface GetAllVestingContractsResponse {
  contracts: VestingContractRecord[];
}
export interface VestingContractRecord {
  address: string;
  contract_address: string;
}
export interface InstantiateMsg {
  owner?: string | null;
}
export type QueryMsg =
  | {
      vesting_contract: {
        address: string;
      };
    }
  | {
      get_all_vesting_contracts: {
        limit?: number | null;
        start_after?: string | null;
      };
    };
export interface VestingContractResponse {
  address: string;
  contract_address?: string | null;
  found: boolean;
}
